--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VennDev/VVanillaMobs
build-by-default: true
branches:
- main
projects:
  VVanillaMobs:
    path: ""
    libs:
      - src: VennDev/LibVapmPMMP/LibVapmPMMP
        version: 1.7.5
        branch: "main"
...
