<?php

/**
 * VSharedData - PocketMine plugin.
 * Copyright (C) 2023 - 2025 VennDev
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace vennv\vvanillamobs\entity;

use pocketmine\entity\EntitySizeInfo;
use pocketmine\entity\Living;
use pocketmine\entity\Location;
use pocketmine\nbt\tag\CompoundTag;

class BaseEntity extends Living {

    public function __construct(
        Location $location, ?CompoundTag $nbt = null
    ) {
        parent::__construct($location, $nbt);
    }

    public function getName() : string {
        return "BaseEntity";
    }

    public function getDrops() : array {
        return [];
    }

	public function initEntity(CompoundTag $nbt) : void {
		parent::initEntity($nbt); // TODO: Change the autogenerated stub
	}

	protected function getInitialSizeInfo() : EntitySizeInfo {
        return new EntitySizeInfo(1.0, 1.0);
    }

    public static function getNetworkTypeId() : string {
        return "BaseEntity";
    }

}